kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-role
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["namespaces","pods","deployments","nodes"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-binding
subjects:
- kind: ServiceAccount
  name: serviceaccount-sa
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: monitoring-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  
  name: serviceaccount-sa
  namespace: monitoring
secrets:
 - name: serviceaccount-sa-token


